### ISSUE TITLE
Vercel doesn't want to deploy anything until we upgrade to node 18

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/github-issue-search-client#115]
As seen in https://github.com/silverstripe/github-issue-search-client/pull/113, Vercel isn't deploying anything for us right now.
Looking at the deployment overview, vercel shows this error:
> Error: Node.js Version "12.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.

It's been a while since we've really looked at this repo properly - probably worth updating all the dependencies at the same time so long as that doesn't cause any major issues.

## Acceptance criteria
- [x] The project is compatible with node 18
- [x] If feasible, dependencies are updated to their latest versions
- [x] The vercel project is updated to use node 18
- [ ] The updated changes are deployed and working as expected.

## PRs
- https://github.com/silverstripe/github-issue-search-client/pull/116

**Comment by emteknetnz** [comment]
@GuySartorelli assigned back to you to confirm deployment works

**Comment by GuySartorelli** [comment]
Deployment successful: https://vercel.com/silverstripe/github-issue-search-client/9YqQuc8pubb9aNPNHgcBMUhV6coq
