### ISSUE TITLE
Add "community contributions only" checkbox

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/github-issue-search-client#128]
I regularly use this to check for community contributions that might need attention. Sometimes it's hard to see the community contributions inbetween all of the CMS Squad stuff, so it would be nice to have a checkbox to be able to view just the community contributions.

## PRs
- https://github.com/silverstripe/github-issue-search-client/pull/129

**Comment by emteknetnz** [comment]
Linked PR merged
