### ISSUE TITLE
Moving away from Vercel

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/github-issue-search-client#139]
Vercel says we'll have to pay in 6 months. When Elvis was originally envision, GitHub action didn't exist.

We can probably move away from vercel and use GitHub Action+Pages instead. That will allow us to remove a redundant tool from our tech stack.

## Notes
- Refer to https://github.com/silverstripe/github-issue-search-client/issues/121 for all the domains (and seemingly separate host sources) we currently have for this

## Acceptance criteria
- [x] Elvis deployment and hosting is moved to GitHub Actions and GitHub Pages.
- [x] Elvis deployment and development doc is updated to reflect any changes to the applications.
- [x] A `something.silverstripe.org` domain is configured and points to the GitHub pages.
- ~Vercel domain redirect to the new GitHub Pages domain (Maybe that's not worth trouble)~
- [x] Any reference to Elvis in the official dev docs or repo doc is updated to point to the new URL
- [x] [Asset page](https://silverstripe.atlassian.net/wiki/spaces/PROD/pages/edit-v2/1493958687) on confluence is updated

## PRs
- https://github.com/silverstripe/github-issue-search-client/pull/142
- https://github.com/silverstripe/developer-docs/pull/544
- https://github.com/silverstripe/github-issue-search-client/pull/143

**Comment by GuySartorelli** [comment]
I've started the process of getting a subdomain - https://servicedesk.silverstripe.cloud/support/tickets/149740

**Comment by emteknetnz** [comment]
Have merged PR - looks good - https://silverstripe.github.io/github-issue-search-client/

Reassigned to Guy to do all the follow up tasks
