### ISSUE TITLE
Spelling errors cause misses in possible hits

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/github-issue-search-client#48]
https://slackarchive.silverstripe.org/slack-archive/message/272447#msg_272447

As per the message on Slack, a spelling error either in the query or the issue causes a miss

**Comment by robbieaverill** [comment]
I’m not sure what we can do about that really. It’s essentially a wrapper for a GitHub search, which would also have the same issue

**Comment by Firesphere** [comment]
Me neither, I'm only forwarding the message because this repo is not publicly available :)

**Comment by robbieaverill** [comment]
I guess a client side library to detect and add extra search terms for suggested typos might work

**Comment by robbieaverill** [comment]
Quick side note, this repo is public
